### ISSUE TITLE
limit to only installed versions

### ISSUE THREAD

**Issue by jasonkarns** [hurrymaplelad/nodenv-package-json-engine#3]
Awesome plugin!

Do you have any thoughts around restricting the version to those that are installed? As it stands now (correct me if I'm wrong), the plugin will select the maximum version that satisfies the version spec from `versions`, regardless whether that version is installed on the machine or not. This would mean that the moment semver.io sees new versions, my local install will stop working. Correct?

I [opened an issue](https://github.com/heroku/semver.io/issues/51) for discussion at semver.io to accept a list of versions to match against (still satisfying the semver spec, of course) but I don't have much hope that it would be implemented since the feature is kind of an edge case for them.

As an alternative, we could modify the semver spec from package.json by appending the max installed version. (`nodenv versions` is already a sorted list. We would just need to grab the last one listed, excluding iojs versions; prepend `<=` to it, and then append that to the semver.io query) This would effectively limit the semver.io response to installed versions.

Given specified engine: `>=4.0.0`
Given installed versions: 4.0.0, 4.1.0, 4.2.1
semver.io (given >= 4.0.0) would return 5.0.0
but if we query semver.io with `>=4.0.0 <=4.2.1` the response would be `4.2.1`

In the case that none of the installed versions match the supplied engine spec, we could default to semver.io's standard query:

Given specified engine: `>=4.0.0`
Given installed versions: 0.10.0, 0.12.0
semver.io: `>=4.0.0 <=0.12.0` returns 5.0.0 (seems to return max available if semver spec excludes everything)

**Comment by hurrymaplelad** [comment]
Thanks Jason!  I totally agree with the direction you're thinking!  The way it works now was just the quickest first pass and could definitely be better.  Lots of thoughts on how to get there.

As a short term fix, on projects where I need a stable node version and only want to upgrade intentionally, I code an explicit version rather than a range  into my package.json.

For projects that could use lots of different node versions, the next plugin I want to write is an auto-installer for missing versions so you'll always be up to date.

I think this plugin should let you keep your currently installed version if it matches your package semver (perhaps behind a flag in case you want to be warned when a newer version is available).  I bet we could do that comparison locally (is there a semver shell script yet?) to avoid the network dependency for the common path.

**Comment by jasonkarns** [comment]
> I think this plugin should let you keep your currently installed version if it matches your package semver

that's a great idea. I was only thinking of comparing installed nodes vs package.json vs semver.io; but you're right. You could also figure out what the currently selected node version is, and just leave it un-modified if it matches package.json

> I code an explicit version rather than a range  into my package.json.

Agreed. I think there are two common situations. For libraries and modules, the engine is typically specified with a loose version spec. For apps, OTOH, the version spec tends to be much tighter, even to exact versions.

**Comment by hurrymaplelad** [comment]
This looks promising: https://github.com/qzb/sh-semver
